[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking attacks
    X-Frame-Options = "DENY"
    # Enable XSS protection
    X-XSS-Protection = "1; mode=block"
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    # Enable strict HTTPS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https:; frame-ancestors 'none';"
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

[[redirects]]
from = "/*"
to = "/index.html"
status = "200"
